### ISSUE TITLE
Having to restart xremap user service after restarting system

### ISSUE THREAD

**Issue by mchowning** [xremap/nix-flake#18]
When I restart my system, xremap does not work until I restart the service. I'm not sure if there's a configuration issue on my end or if there is something not working as expected with the xremap flake. I appreciate any help.

I have checked and confirmed that the xremap service is running after I restart my computer:

```
❯ systemctl --user status xremap.service
● xremap.service - xremap user service
     Loaded: loaded (/etc/systemd/user/xremap.service; enabled; preset: enabled)
     Active: active (running) since Sat 2023-03-11 21:13:19 EST; 16s ago
   Main PID: 1829 (xremap)
      Tasks: 1 (limit: 18894)
     Memory: 3.4M
        CPU: 10ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/xremap.service
             └─1829 /nix/store/xl4aydyzv4kamr9qfk5wl8m7js6lb0a9-xremap-0.8.0/bin/xremap /nix/store/1i5bgym05v8i5cgwjqm9hcl0l64qgdp1-xremap-config.yml

Mar 11 21:13:19 nixos xremap[1829]: /dev/input/event6 : Video Bus
Mar 11 21:13:19 nixos xremap[1829]: /dev/input/event7 : AT Translated Set 2 keyboard
Mar 11 21:13:19 nixos xremap[1829]: /dev/input/event8 : Synaptics TM3289-021
Mar 11 21:13:19 nixos xremap[1829]: /dev/input/event9 : HDA Digital PCBeep
Mar 11 21:13:19 nixos xremap[1829]: ------------------------------------------------------------------------------
Mar 11 21:13:19 nixos xremap[1829]: Selected keyboards automatically since --device options weren't specified:
Mar 11 21:13:19 nixos xremap[1829]: Failed to grab device 'AT Translated Set 2 keyboard' at '/dev/input/event0' due to: Device or resource busy (os error 16)
Mar 11 21:13:19 nixos xremap[1829]: ------------------------------------------------------------------------------
Mar 11 21:13:19 nixos xremap[1829]: /dev/input/event7 : AT Translated Set 2 keyboard
Mar 11 21:13:19 nixos xremap[1829]: ------------------------------------------------------------------------------
```

But my xremap bindings don't work until I run `systemctl --user restart xremap.service`, after which I can check the service's status and it looks the identical to how it looked before restarting the service (i.e., the same as I pasted above), but now my xremap bindings work.

Here's the xremap portion of my NixOS config:

``` nix
services.xremap = {
  serviceMode = "user";
  withGnome = true;
  userName = username;
  config = { ... };
};
```

Thanks for putting together this flake. I've enjoyed using it, I'm just a bit stumped as to what is happening here.

**Comment by VTimofeenko** [comment]
Hi! I use xremap with user service on sway-wm. Sway officially does not support systemd integration requiring various hacks around the user services and their ordering. Case in point - I have `systemctl --user restart xremap` ran every time my sway session starts.

The gnome code in this flake was based on sway, so that's probably the explanation for what you are experiencing. However, Gnome should play better with systemd, so it's most likely possible to order units in a way that would not require such a restart. 

I'll look into it.

**Comment by VTimofeenko** [comment]
I was actually not able to reproduce this. The latest master branch has a new nixosConfiguration with a minimal Gnome config ([link](https://github.com/xremap/nix-flake/blob/e90a9543d42bda5995e112a4e7eea2b559f3e979/flake.nix#L143)). This config works for a couple of trivial remaps (9 -> 0 across the board, a -> b only in kitty) without any restarts. On top of config I did have to manually enable the xremap Gnome extension in the "Extensions" app. It's probably possible to do this from nix but I don't have a lot of experience with Gnome on nix :)

One potential difference is that the flake follows nixpkgs-unstable and your system flake may be following 22-05.

Can you extract a minimal configuration to reproduce this from your system config?

**Comment by mchowning** [comment]
Thanks for taking some time to look into this. :bow: 

> This config works for a couple of trivial remaps (9 -> 0 across the board, a -> b only in kitty) without any restarts.

I tried this out as well and realized that these worked fine for me too. I did some more digging and it turns out that I'm only experiencing the issue where I have to restart the service after restarting my computer for bindings that use [wmctrl](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/tools/X11/wmctrl/default.nix) to switch windows, for example:

``` nix
Key_w = {
  launch = [
    "${pkgs.bash}/bin/bash"
    "-c"
    "${pkgs.wmctrl}/bin/wmctrl -x -a google-chrome"
  ];
};
```

I'm still trying to figure out what is the underlying issue (and whether it is with wmctrl or xremap).

**Comment by VTimofeenko** [comment]
I think I was able to replicate this while working on #19

**Comment by VTimofeenko** [comment]
I was right, on GNOME it needed `gnome-session.target` by which DISPLAY: and other stuff are set. Fixed on master, sample config is available in nixosconfigurations

**Comment by mchowning** [comment]
Thakns so much @VTimofeenko !
