### ISSUE TITLE
Malformed config

### ISSUE THREAD

**Issue by jevy** [xremap/nix-flake#19]
Howdy!

I'd like to launch something with a keypress but it looks like I might be doing something wrong:

```nix
{
  config.services.xremap = {
    serviceMode = "user";
    userName = "jevin";
    withSway = true;
    config = {
      modmap = [
        {
          remap = {
            KEY_F24 = {
              press = { launch = ["kitty"]; };
              release = {};
            };
          };
        }
      ];
    };
  };
}
```

Generates:
```json
{"modmap":[{"remap":{"KEY_F24":{"press":{"launch":["kitty"]},"release":{}}}}]}
```

But I get the error:
`Error: Failed to load config '/nix/store/3984zw5834r1yrayvn5hzs8068y45rrm-xremap-config.yml': modmap[0].remap: data did not match any variant of untagged enum ModmapAction at line 1 column 21`

It _looks_ like the same as the [documented example here](https://github.com/k0kubun/xremap#modmap)

**Comment by VTimofeenko** [comment]
Hi! Looks like my original idea of "let's use JSON in place of YAML, they're pretty close" finally caught up with me.

In this case the original config uses an embedded object for the remap definition which is probably not doable with json.

A fix is to rework the module in this flake and add a `.configFile` setting that is mutually exclusive with `.config`. This setting allows the user to pass arbitrary text content.

Should not be complex, I'll take care of it this week.

**Comment by VTimofeenko** [comment]
Also, if you don't care about `release` value and only want to map F24 to launching something - you can probably try something like [this](https://github.com/xremap/nix-flake/issues/18#issuecomment-1485485862) even without the new module option.

**Comment by VTimofeenko** [comment]
> When I looked at the code and saw the nix (It was nix right? Not json?) -> yaml conversion I thought that was pretty clever.

Actually it was nix -> JSON conversion. Nix (arguably) is just JSON with functions. Converting to nix to YAML if I recall correctly needs `pkgs` and is architecture-dependant, whereas nix to JSON is a part of standard library.  YAML and JSON are very close but YAML is kind of a superset of JSON.

Looks like the README of xremap is a bit wrong - an object is not needed, but if `press` is set - `release` also needs to be set and non-empty. The object notation there is not needed.

Anyway, `.yamlConfig` option now exists. See [this](https://github.com/xremap/nix-flake/blob/master/flake.nix#L175) config for an example of launching kitty by hitting "9" on keyboard. The issues in xremap repo contain a sample config for a "Launcher" mode which activates certain keybinds if the mode is entered.
