### ISSUE TITLE
`home-manager` module

### ISSUE THREAD

**Issue by hab25** [xremap/nix-flake#20]
Would be great for non-NixOS nix users.  I think most would be okay with having to manually setup the proper permissions (https://github.com/k0kubun/xremap/blob/1b09e4dbdf78ab3a19573e7f8f579eb0d936212e/README.md?plain=1#L65) outside of nix, as that process is very simple.

**Comment by VTimofeenko** [comment]
Done, flake on the master branch has the `homeManagerModules` output with the systemd user service. Seems to work fine on a non-NixOS KDE machine.
