### ISSUE TITLE
Provide a snippet showcasing how to use the flake

### ISSUE THREAD

**Issue by jacob-emery** [xremap/nix-flake#26]
Hi, I suggest adding a snippet showcasing how to use the module. I have been trying myself, unsuccessfully. It would help people that have just started using flakes/nixos.

I added the flake to my `inputs`, however since I am fairly new to nixos I am struggling to correctly import the module.

```nix
{
    inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    programsdb = {
      url = "github:wamserma/flake-programs-sqlite";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    xremap-flake.url = "github:xremap/nix-flake";
  };
  
  outputs = { self, nixpkgs, programsdb, xremap-flake }@inputs:
    let
      pkgs-lib = nixpkgs.lib;
      mkHost = { zfs-root, pkgs, dbPath, system, ... }:
        pkgs-lib.nixosSystem {
          inherit system;
          modules = [
            ./modules
            # xremap-flake.nixosModules.default # i tried uncommenting this. It was unsuccessful...
            (import ./configuration.nix { inherit zfs-root inputs pkgs pkgs-lib dbPath; })
            ({...}: {
              nix.settings.experimental-features = [ "nix-command" "flakes" ];
              nix.registry.pkgs.flake = nixpkgs;              
            })
          ];
        };
    in {
      nixosConfigurations = {
        my-hostname = let
          pkgs = nixpkgs.legacyPackages.${system};
          system = "x86_64-linux";
          dbPath = programsdb.packages.${pkgs.system}.programs-sqlite;
        in mkHost (import ./hosts/my-hostname { inherit system pkgs dbPath ; });
      };
    };
}
```

Also when searching for `xremap` in  `man configuration.nix`, I cannot find any results.

**Comment by VTimofeenko** [comment]
Hi! There are some sample configs available in the [development VM configurations](https://github.com/xremap/nix-flake/blob/a2295e6bf755a313cb54aaf7a08beb8f00cfb4ec/nixosConfigurations/default.nix#L6). But you're right, that's not very accessible. I'll add a proper sample to the README.

>             # xremap-flake.nixosModules.default # i tried uncommenting this. It was unsuccessful...

What happens when you uncomment and nixos-rebuild? Could you post the full error message please?

> Also when searching for xremap in man configuration.nix, I cannot find any results.

That is expected, since the xremap-flake is not part of the standard configuration.

**Comment by VTimofeenko** [comment]
@jacob-emery I have added a sample config to the README. Can you check if config like that example would work for you?

**Comment by VTimofeenko** [comment]
There's a number of things in HOWTO.md now.
