### ISSUE TITLE
Application-specific remapping does not work as expected

### ISSUE THREAD

**Issue by caiguo37** [xremap/nix-flake#27]
I'm using xremap with home-manager and everything works fine except for the application specific remapping.

```nix
{
  config,
  pkgs,
  inputs,
  ...
}: {
  imports = [
    inputs.xremap-flake.homeManagerModules.default
  ];
  services.xremap = {
    withGnome = true;
    yamlConfig = ''
      keymap:
        - name: Terminal
          application:
            only: Alacritty
          remap:
            Super-b: C-b
            Super-f: C-f
    '';
  };
```

The configuration file above  have no effect.  I think the application name is OK.
If you remove the application option, this remap takes effect globally.

**Comment by VTimofeenko** [comment]
Do you have the [xremap Gnome extension](https://extensions.gnome.org/extension/5060/xremap/) installed? Can you please post the logs from `journalctl --user -u xremap`?

**Comment by caiguo37** [comment]
9月 13 21:43:14 nixos systemd[1413]: Started xremap service.
9月 13 21:43:14 nixos xremap[2120]: Selecting devices from the following list:
9月 13 21:43:14 nixos xremap[2120]: ------------------------------------------------------------------------------
9月 13 21:43:14 nixos xremap[2120]: /dev/input/event0 : Sleep Button
9月 13 21:43:14 nixos xremap[2120]: /dev/input/event1 : Power Button
9月 13 21:43:14 nixos xremap[2120]: /dev/input/event10: Logitech MX518 Gaming Mouse
9月 13 21:43:14 nixos xremap[2120]: /dev/input/event11: Logitech MX518 Gaming Mouse Keyboard
9月 13 21:43:14 nixos xremap[2120]: /dev/input/event12: Logitech ERGO M575
9月 13 21:43:14 nixos xremap[2120]: /dev/input/event13: HDA Intel PCH Line Out
9月 13 21:43:14 nixos xremap[2120]: /dev/input/event14: HDA Intel PCH Front Headphone
9月 13 21:43:14 nixos xremap[2120]: /dev/input/event15: HDA Intel PCH HDMI/DP,pcm=3
9月 13 21:43:14 nixos xremap[2120]: /dev/input/event16: HDA Intel PCH HDMI/DP,pcm=7
9月 13 21:43:14 nixos xremap[2120]: /dev/input/event17: HDA Intel PCH HDMI/DP,pcm=8
9月 13 21:43:14 nixos xremap[2120]: /dev/input/event18: HHKB-Hybrid_2 Keyboard
9月 13 21:43:14 nixos xremap[2120]: /dev/input/event2 : Power Button
9月 13 21:43:14 nixos xremap[2120]: /dev/input/event3 : Video Bus
9月 13 21:43:14 nixos xremap[2120]: /dev/input/event4 : HDA ATI HDMI HDMI/DP,pcm=3
9月 13 21:43:14 nixos xremap[2120]: /dev/input/event5 : HDA ATI HDMI HDMI/DP,pcm=7
9月 13 21:43:14 nixos xremap[2120]: /dev/input/event6 : HDA ATI HDMI HDMI/DP,pcm=8
9月 13 21:43:14 nixos xremap[2120]: /dev/input/event7 : HDA ATI HDMI HDMI/DP,pcm=9
9月 13 21:43:14 nixos xremap[2120]: /dev/input/event8 : HDA ATI HDMI HDMI/DP,pcm=10
9月 13 21:43:14 nixos xremap[2120]: /dev/input/event9 : HDA ATI HDMI HDMI/DP,pcm=11
9月 13 21:43:14 nixos xremap[2120]: ------------------------------------------------------------------------------
9月 13 21:43:14 nixos xremap[2120]: Selected keyboards automatically since --device options weren't specified:
9月 13 21:43:15 nixos xremap[2120]: ------------------------------------------------------------------------------
9月 13 21:43:15 nixos xremap[2120]: /dev/input/event11: Logitech MX518 Gaming Mouse Keyboard
9月 13 21:43:15 nixos xremap[2120]: /dev/input/event18: HHKB-Hybrid_2 Keyboard
9月 13 21:43:15 nixos xremap[2120]: ------------------------------------------------------------------------------
9月 13 21:43:40 nixos xremap[2120]: application-client: GNOME (supported: false)
9月 13 21:54:03 nixos systemd[1413]: Stopping xremap service...
9月 13 21:54:03 nixos systemd[1413]: Stopped xremap service.
-- Boot 1bfc26e1d8234193914fd66ee4bfc407 --
9月 13 21:54:36 nixos systemd[1402]: Started xremap service.
9月 13 21:54:37 nixos xremap[2083]: Selecting devices from the following list:
9月 13 21:54:37 nixos xremap[2083]: ------------------------------------------------------------------------------
9月 13 21:54:37 nixos xremap[2083]: /dev/input/event0 : Sleep Button
9月 13 21:54:37 nixos xremap[2083]: /dev/input/event1 : Power Button
9月 13 21:54:37 nixos xremap[2083]: /dev/input/event10: Logitech MX518 Gaming Mouse
9月 13 21:54:37 nixos xremap[2083]: /dev/input/event11: Logitech MX518 Gaming Mouse Keyboard
9月 13 21:54:37 nixos xremap[2083]: /dev/input/event12: Logitech ERGO M575
9月 13 21:54:37 nixos xremap[2083]: /dev/input/event13: HDA Intel PCH Line Out
9月 13 21:54:37 nixos xremap[2083]: /dev/input/event14: HDA Intel PCH Front Headphone
9月 13 21:54:37 nixos xremap[2083]: /dev/input/event15: HDA Intel PCH HDMI/DP,pcm=3
9月 13 21:54:37 nixos xremap[2083]: /dev/input/event16: HDA Intel PCH HDMI/DP,pcm=7
9月 13 21:54:37 nixos xremap[2083]: /dev/input/event17: HDA Intel PCH HDMI/DP,pcm=8
9月 13 21:54:37 nixos xremap[2083]: /dev/input/event18: HHKB-Hybrid_2 Keyboard
9月 13 21:54:37 nixos xremap[2083]: /dev/input/event2 : Power Button
9月 13 21:54:37 nixos xremap[2083]: /dev/input/event3 : Video Bus
9月 13 21:54:37 nixos xremap[2083]: /dev/input/event4 : HDA ATI HDMI HDMI/DP,pcm=3
9月 13 21:54:37 nixos xremap[2083]: /dev/input/event5 : HDA ATI HDMI HDMI/DP,pcm=7
9月 13 21:54:37 nixos xremap[2083]: /dev/input/event6 : HDA ATI HDMI HDMI/DP,pcm=8
9月 13 21:54:37 nixos xremap[2083]: /dev/input/event7 : HDA ATI HDMI HDMI/DP,pcm=9
9月 13 21:54:37 nixos xremap[2083]: /dev/input/event8 : HDA ATI HDMI HDMI/DP,pcm=10
9月 13 21:54:37 nixos xremap[2083]: /dev/input/event9 : HDA ATI HDMI HDMI/DP,pcm=11


and **gnomeExtensions.xremap** is installed.

**Comment by caiguo37** [comment]
I know what the problem is. I installed gnomeExtension.xremap, but didn't enable it.
It's works perfect now. 

Good app, thank u,  @VTimofeenko

**Comment by VTimofeenko** [comment]
Awesome, glad it works :)

For the record, here's what the log looks like with a supported desktop manager:

```
...
Aug 05 20:54:40 uranium xremap[2574]: /dev/input/event9 : HDA Intel PCH HDMI/DP,pcm=8
Aug 05 20:54:40 uranium xremap[2574]: ------------------------------------------------------------------------------
Aug 05 20:54:40 uranium xremap[2574]: Selected keyboards automatically since --device options weren't specified:
Aug 05 20:54:40 uranium xremap[2574]: ------------------------------------------------------------------------------
Aug 05 20:54:40 uranium xremap[2574]: /dev/input/event1 : AT Translated Set 2 keyboard
Aug 05 20:54:40 uranium xremap[2574]: ------------------------------------------------------------------------------
Aug 05 20:54:48 uranium xremap[2574]: application-client: Hypr (supported: true)
Aug 05 20:54:48 uranium xremap[2574]: application: kitty
Aug 05 20:54:56 uranium xremap[2574]: application: firefox
```
