### ISSUE TITLE
Warning about missing mainProgram attribute

### ISSUE THREAD

**Issue by raphaelweis** [xremap/nix-flake#28]
So I have setup xremap as a home manager module in my flake, and everytime I rebuild, I get this warning:
```
warning: getExe: Package "xremap-0.8.7" does not have the meta.mainProgram attribute. 
We'll assume that the main program has the same name for now, but this behavior is deprecated, 
because it leads to surprising errors when the assumption does not hold. 
If the package has a main program, please set meta.mainProgram in its definition to make this warning go away. 
Otherwise, if the package does not have a main program, or if you don't control its definition, 
use getExe' to specify the name to the program, such as lib.getExe' foo "bar".
```
<details>
<summary>My xremap flake configuration</summary>
<br>

```nix
# flake.nix:
inputs.xremap.url = "github:xremap/nix-flake";

# ...

outputs = { ... }@inputs:
  let
    system = "x86_64-linux";
    pkgs = import inputs.nixpkgs {
      inherit system;
      config.allowUnfree = true;
    };

    # ...

  in
  {

    # ...

    homeConfigurations = {
      "orange" = inputs.home-manager.lib.homeManagerConfiguration {
        inherit pkgs;
        modules = [ ./home.nix ];
        extraSpecialArgs = { inherit pkgs inputs; };
      };
    };
  };
}

# home.nix
{ vars, ... }:
{
  imports = [

    # ...

    (import ../../features/home-manager/xremap)
  ];

  home = {
    username = vars.username;
    homeDirectory = "/home/${vars.username}";
    stateVersion = "22.11";
  };

  programs = {
    home-manager.enable = true;
  };
}

# xremap.nix
{ inputs, ... }:
{
  imports = [ inputs.xremap.homeManagerModules.default ];
  services.xremap = {
    config = {
      keymap = [
        # vim style navigation
        {
          name = "Go Left";
          remap = {
            "ALT-h" = "left";
          };
        }

        # ...

      ];
    };
  };
}
```
</details>
 
My config works just fine even with the warning, and I have no issues using xremap, I was just wondering if it's a config error on my part or if the attribute is really missing from the flake. I have tried setting the `package` option but could not get it to work, and I encountered the exact same warning when using the nixosModule instead of the home-manager one.
I looked a little bit in the code of the flake but being no nix expert I was not able to find the declaration of this attribute.
I also don't really know how to use the lib.getExe method mentioned in the warning message.

Has anyone encountered the same issue ? Again, this configuration is completely functional, even with the warning.

**Comment by VTimofeenko** [comment]
Well that's a bit embarrassing -- during the migration to flake-parts I misplaced the meta attribute.

> I encountered the exact same warning when using the nixosModule instead of the home-manager one.
This is odd, sine the line that produces error is this (in homeManagerModule):

```
❯ rg getExe
homeManagerModules/default.nix
19:        ExecStart = "${lib.getExe cfg.package} ${if cfg.deviceName != "" then "--device \"${cfg.deviceName}\"" else ""} ${if cfg.watch then "--watch" else ""} ${configFile}";
``` 

It's not in the normal modules. In any case, I will add the `meta.mainProgram` and the problem will go away.

Isolated test can be done from a flake like so:

```
❯ cat flake.nix
{
  description = "A very basic flake";

  inputs.xremap.url = "<THE_PATH_TO_XREMAP_FLAKE>";

  outputs = inputs@{ self, nixpkgs, ... }:
    let
      system = "x86_64-linux";
    in
    {
      apps."${system}".default = {
        type = "app";
        program = nixpkgs.legacyPackages.${system}.lib.getExe inputs.xremap.packages.${system}.default;
      };
    };
}
❯ nix run .#
.... # warning will be thrown here
```

**Comment by raphaelweis** [comment]
Thank you! And don´t worry about the nixosModule part, it was probably an error on my end, or even my memory failing me.

**Comment by VTimofeenko** [comment]
Oh, no worries and thanks for reporting this!
