### ISSUE TITLE
Importing nixosModule results in error

### ISSUE THREAD

**Issue by stfnx** [xremap/nix-flake#30]
I added the Flake to my inputs, but importing `inputs.xremap.nixosModules.default` results in the following issue:

```
error: assertion '((((cfg).yamlConfig == "") && ((cfg).config != { })) || (((cfg).yamlConfig != "") && ((cfg).config == { })))' failed

       at /nix/store/wib2g0yxb1vyy7mglkysjllpxri76jd9-source/modules/system-service.nix:9:7:

            8|     text =
            9|       assert ((cfg.yamlConfig == "" && cfg.config != { }) || (cfg.yamlConfig != "" && cfg.config == { }));
             |       ^
           10|       if cfg.yamlConfig == "" then pkgs.lib.generators.toYAML { } cfg.config else cfg.yamlConfig;
(use '--show-trace' to show detailed location information)
```

Importing the `inputs.xremap.homeManagerModules.default` worked without any issues.

**Comment by VTimofeenko** [comment]
The assertion is put in place to check that one and only one of `[services.xremap.yamlConfig services.xremap.config]` is specified. Note to self: replace this with `lib.asserts.assertMsg` to make the error clear.

The `homeManagerModules.default` uses the same logic to generate the config file with the same assertion, so it's odd that hm module works but the standard one does not. When you used that import did you change other parts the configuration? Can you post it please?

**Comment by stfnx** [comment]
> When you used that import did you change other parts the configuration? Can you post it please?

No I didn't specify any configuration at this point. I just imported the module and ran `nix flake check` to update the lockfile.

**Comment by VTimofeenko** [comment]
Ok, in that case an error is expected, since xremap needs some config to be functional. I'll make a proper error message.

For a sample config -- check out spoiler part of README or one of the development VMs.

**Comment by VTimofeenko** [comment]
Ok, now all config logic should be consistent
