### ISSUE TITLE
Issue with list in sample config?

### ISSUE THREAD

**Issue by stfnx** [xremap/nix-flake#32]
Currently there are some lines in the example config where I'm a little confused.
https://github.com/xremap/nix-flake/blob/87eb623781f2b95eef1e48bdabc8d714bcf26323/README.md?plain=1#L55-L58

When using the above example and running `nix flake check`, I get `syntax error, unexpected '='` (at `name = "Global"`). Which seems to make sense, because I don't think a list can contain a mapping of `name=value`. But I couldn't find an absolute answer [here](https://nixos.org/manual/nix/stable/language/values#list).

I tried to replace the list with an attribute set like so:
```
modmap = {
  name = "Global";
  remap = { "CapsLock" = "Esc"; };  # globally remap CapsLock to Esc
};
```

Nix accepts that and builds successfully, but the xremap service fails to start: `Failed to load config '/nix/store/...-xremap-config.yml': modmap: invalid type: map, expected a sequence at line 1 column 11`, so here a list would be expected...

Something here must be wrong.

I ended up using `yamlConfig` instead of `config` as a workaround, but obviously I'd prefer writing it in Nix.

**Comment by VTimofeenko** [comment]
The example was indeed wrong. `config` is an attrset with <= two keys expected -- `keymap` and `modmap`. They, in turn, should be lists of attrsets.

**Comment by stfnx** [comment]
I can confirm that the corrected example works. Thanks!

**Comment by VTimofeenko** [comment]
Awesome, and thank you so much for the bug reports

**Comment by VTimofeenko** [comment]
Separating the  "nix accepts the config" <=> "xremap accepts the config" part to #45
