### ISSUE TITLE
Feature Request: Mouse option

### ISSUE THREAD

**Issue by stfnx** [xremap/nix-flake#33]
For my config to work I need to run xremap with the `--mouse` option. (See [here](https://github.com/k0kubun/xremap/discussions/356#discussioncomment-7270190))

Currently its not possible to set this option in the Nix Flake.
Would be super cool if this option could be added.

The option `extraArgs` could be useful too. So you could pass additional arguments that are not yet implemented in the Flake.

**Comment by VTimofeenko** [comment]
@stfnx can you please try the latest version that includes `--mouse`?

**Comment by stfnx** [comment]
First of all: Thanks for your effort and the quick response time. Awesome! 🚀
Sure enough I'll test it.

I've added `mouse = true;` to my config, but it doesn't seem to pass the option to xremap:

```
❯ systemctl status xremap.service
● xremap.service - xremap system service
     Loaded: loaded (/etc/systemd/system/xremap.service; enabled; preset: enabled)
     Active: active (running) since Mon 2023-10-16 19:48:47 CEST; 4min 12s ago
   Main PID: 296075 (xremap)
         IP: 0B in, 0B out
         IO: 1.0K read, 0B written
      Tasks: 1 (limit: 18680)
     Memory: 2.1M
        CPU: 615ms
     CGroup: /system.slice/xremap.service
             └─296075 /nix/store/gwzya6iln32lbypdbqzk0ag8n8ldygxj-xremap-0.8.11/bin/xremap --device "Logitech MX Master 2S" --watch /nix/store/nng145i8frrmrr19ays9gssa7isdp6r4-xremap-config.yml
```

**Comment by stfnx** [comment]
> Should work now

Yes it does. :)
