### ISSUE TITLE
KDE (Wayland) support in flake

### ISSUE THREAD

**Issue by karthink** [xremap/nix-flake#35]
I have xremap running via home-manager as a systemd user service with the following options:

```nix
services.xremap = {
  withHypr = true;
  withX11 = true;
  watch = true;
}
```

This works fine on KDE X11 (possibly because of `withX11`), but not on KDE Wayland -- the modmap section of the config works but not any of the other keybindings.

The log displays errors like the following (journalctl output):
```
Oct 15 09:56:19 t14 xremap[1377678]: Reconnecting to X11 due to error: X11 error X11Error { error_kind: Window, error_code: 3, sequence: 7, bad_value: 0, minor_opcode: 0, major_opcode: 20, extension_name: None, request_name: Some("GetProperty") }
Oct 15 09:56:19 t14 xremap[1377678]: Reconnecting to X11 due to error: X11 error X11Error { error_kind: Window, error_code: 3, sequence: 2, bad_value: 0, minor_opcode: 0, major_opcode: 15, extension_name: None, request_name: Some("QueryTree") }
Oct 15 09:56:46 t14 xremap[1377678]: Reconnecting to X11 due to error: X11 error X11Error { error_kind: Window, error_code: 3, sequence: 7, bad_value: 0, minor_opcode: 0, major_opcode: 20, extension_name: None, request_name: Some("GetProperty") }
Oct 15 09:56:46 t14 xremap[1377678]: Reconnecting to X11 due to error: X11 error X11Error { error_kind: Window, error_code: 3, sequence: 2, bad_value: 0, minor_opcode: 0, major_opcode: 15, extension_name: None, request_name: Some("QueryTree") }
```

Does the flake need a separate `withKde` option to enable support for KDE Wayland?

-----

My config is below:

```yaml
modmap:
  - name: caps2ctrl
    remap:
      KEY_CAPSLOCK:
        held: [CTRL_L]
        alone: [ESC]
keymap:
  - name: Emacs bindings in krunner
    application:
      only: [krunner, plasmashell]
    remap:
      C-b: left
      C-f: right
      C-p: up
      C-n: down
      M-d: C-delete
      M-f: C-right
      M-b: C-left
      C-a: home
      C-e: end
      C-d: delete
      C-g: esc
      C-w: C-backspace
      C-k: [ {set_mark: false}, Shift-end, backspace ]
```

**Comment by VTimofeenko** [comment]
Yeah, `withKDE` option is not yet in the flake. Needs #34 first

**Comment by VTimofeenko** [comment]
Also, for the record, multiple `with` results in one of them winning (see #4)

**Comment by evanrichter** [comment]
@VTimofeenko I left a comment on your commit for KDE option, but I've never seen how notifications work in that case... so here's a ping :)

**Comment by VTimofeenko** [comment]
Thanks, I corrected that line. Try the latest commit in the branch?

I also did the notification from the inline comment

**Comment by evanrichter** [comment]
> I also did the notification from the inline comment

good to know thanks!

> Try the latest commit in the branch?

it compiles and creates my config.yml in the store, but I guess I need to logout/login or restart? systemctl says there is no service found `xremap.service` when I try to manually start it, even though there are service definition files in the store

**Comment by VTimofeenko** [comment]
How are you running the flake? Home manager, Nixos?

> systemctl says there is no service found xremap.service when I try to manually start it

Did you run `systemctl --user` ? System `systemctl` does not show users' services, and `withKDE` creates user service.

**Comment by karthink** [comment]
@VTimofeenko Thank you for the very quick turnaround. I'll try the latest commit when I'm back at my nixos machine.

**Comment by evanrichter** [comment]
Ah yes, `systemctl --user` (and for journalctl) indeed shows it. And it's failing to start due to `Error: Failed to prepare an output device: Permission denied (os error 13)` so I probably have to logout/login to apply the `inputs` group to my user

**Comment by VTimofeenko** [comment]
@evanrichter, yeah, your login session gets the list of groups when you log in (check output of `id`), so a re-login is required to properly apply groups*. Does the application specific mapping work correctly for you on KDE?

*: AFAIR technically you can spawn a subshell and get the updated list of groups, but I don't believe there is a way to propagate that into systemd. Re-log is better.

**Comment by karthink** [comment]
@VTimofeenko Did you also address declaration with more than one cargo feature (i.e. x11 && kde && hypr, etc) in the module?

**Comment by VTimofeenko** [comment]
@karthink not yet, I'll do it after KDE is fully tested. Rough order:

- [ ] Have real humans confirm that this works
- [ ] Add VM to test the good path (KDE-specific wayland mapping)
- [ ] Merge
- [ ] Add module checks for #4

**Comment by evanrichter** [comment]
> Does the application specific mapping work correctly for you on KDE?

yes it seems to! with

```nix
      keymap = [
        {
          application.only = "firefox";
          remap = {
            KEY_Q = "KEY_W";
            KEY_W = "KEY_Q";
          };
        }
      ];
```

I have a **wqerty** keyboard in firefox and a **qwerty** keyboard in my terminal :)

**Comment by karthink** [comment]
```sh
warning: updating lock file './flake.lock':
• Updated input 'xremap-flake':
    'github:xremap/nix-flake/1948fe9a0da3727d9de825c160ad8ec106ed0401' (2023-09-22)
  → 'github:xremap/nix-flake/167994d9b03708e9f9a4eda92a053ea7083cc148' (2023-10-16)
• Updated input 'xremap-flake/xremap':
    'github:k0kubun/xremap/47d6932da04bc952b479c0952650615124407176' (2023-09-22)
  → 'github:k0kubun/xremap/be51386e42583255dddc2777c77b1a28defea8d4' (2023-10-10)
error: attribute 'serviceMode' missing

       at /nix/store/k92fv65aic0pbapz37aw7rj2rrz18zi7-source/lib/default.nix:18:32:

           17|       default =
           18|         assert (cfg.withKDE -> cfg.serviceMode == "user") || throw "Upstream does not support running withKDE as root";
             |                                ^
           19|         if cfg.withWlroots then
(use '--show-trace' to show detailed location information)
```

It failed to build with this error. Any idea if I'm doing something wrong?

**Comment by karthink** [comment]
Okay, best I can tell from reading the source, the `serviceMode` option should be declared as part of `commonOptions` in `./lib/default.nix` instead of in `./modules/default.nix`.  This will make `serviceMode` available to `homeManagerModules.default`.

Please excuse me if I got it wrong, I'm new to reading flakes.

**Comment by VTimofeenko** [comment]
You're spot on. The `assert` statement does not take lack of `serviceMode` (which happens for home manager module) into account

**Comment by VTimofeenko** [comment]
@karthink try with the latest commit, I added a check for the lack of serviceMode

**Comment by karthink** [comment]
> @karthink try with the latest commit on withKDE branch, I added a check for the lack of serviceMode

It works! Tested on both KDE X11 and Wayland.
