### ISSUE TITLE
Cannot get home-manager setup to work

### ISSUE THREAD

**Issue by augustebaum** [xremap/nix-flake#38]
Hey,

I'm kind of in the same situation as described in issue #26, first time using an external flake in my Nix config.

I'm failing to adapt the NixOS example in the Readme to the Home-manager-only case. Here's what I have:
```nix
    ...
    nixosConfigurations = {
      my-machine = nixpkgs.lib.nixosSystem {
        system = "x86_64-linux";
        modules = [
          ./configuration.nix
          home-manager.nixosModules.home-manager
          {
            home-manager.useGlobalPkgs = true;
            home-manager.users.auguste = import ./home.nix;
          }
          xremap.homeManagerModules.default
          {
            services.xremap = {
              config = {
                modmap = [
                  {
                    name = "Global";
                    remap = {"CapsLock" = "Esc";}; # globally remap CapsLock to Esc
                  }
                ];
              };
            };
          }
        ];
      };
    };
    ...
```

where I just replaced `inputs.xremap-flake.nixosModules.default` with `xremap.homeManagerModules.default` (as I named the flake input `xremap`) and removed all the options that were causing "unknown option" errors. Now the error I get is:
```
   error: The option `systemd.user.services.xremap.Install' does not exist. Definition values:
       - In `/nix/store/.../homeManagerModules':
           {
             WantedBy = [
               "graphical-session.target"
             ];
           }
```

Any idea what could be causing this? Am I even using this flake output correctly?

Thanks in advance for any feedback :)

**Comment by VTimofeenko** [comment]
The error you're getting:

> The option `systemd.user.services.xremap.Install' does not exist. Definition values:

happens because home manager has a different systemd services syntax compared to NixOS modules. In NixOS a service would look like this:

```nix
{
  systemd.user.services.foo = {
    description = "Foo" # This turns into the service description
    # Some other service fields have a top-level option here
    serviceConfig = {
        # unit settings  go here
        ExecStart = "hello";
    };
  };
}
```

whereas on home manager:

```nix
{
    systemd.user.services.foo = {
        # all unit settings go here
        ExecStart = "hello";
    };
}
```

In the config you provided you're using home manager module as a "system"-level module.

You could get this flake to work in two ways:
1. Use nixosModule:

    1. Replace `xremap.homeManagerModules.default` with `xremap.nixosModules.default`
    2. Add `userName` (like [here](https://github.com/xremap/nix-flake/blob/master/README.md?plain=1#L52)), depending on the features specify `with*` and set `serviceMode` (see the matrix in README) 

2. Import homeManager module in the context of your user

    1. Remove top-level import of `xremap.homeManagerModules.default`
    2. Remove top-level import of the xremap settings
    3. Replace `home-manager.users.auguste = import ./home.nix;` with something along the lines of:

        ```nix
        {
            home-manager.users.auguste = {
                imports = [
                    ./home.nix
                    xremap.homeManagerModules.default
                    {
                        services.xremap = {
                          config = {
                            modmap = [
                              {
                                name = "Global";
                                remap = {"CapsLock" = "Esc";}; # globally remap CapsLock to Esc
                              }
                            ];
                            # other xremap settings go here
                          };
                        };
                     }
                ];
            };
         }
         ```
