### ISSUE TITLE
Allow specifying more than once `deviceName`

### ISSUE THREAD

**Issue by cvincent** [xremap/nix-flake#60]
Per the following issue: https://github.com/k0kubun/xremap/issues/44

xremap automatically remaps all detected keyboards if a device is not specified. To remap a mouse, its name must be specified in the `--device` argument. To remap a mouse _and_ keyboard, you specify `--device` more than once. Looking at this flake, it appears we only have the option to specify a single `--device`. If this option were a list of devices instead, or there were an option like `deviceNames` (plural) that was a list, we could specify multiple devices.

**Comment by VTimofeenko** [comment]
`deviceName` predates the mouse feature, so I have an excuse for painting myself into a corner :)

I think the approach would be:

1. Add `deviceNames` (nullOr list of strings)
2. Deprecate "deviceName" in favor of `deviceNames`
3. In a couple of xremap releases completely remove `deviceName`

Meanwhile `extraArgs` could be used as a workaround
