### ISSUE TITLE
Mappings defined across multiple modules are not merged

### ISSUE THREAD

**Issue by undyamon** [xremap/nix-flake#62]
Having two modules defining their own mappings, does not result in the union of all mappings. As an example,

```nix
# modA.nix
services.xremap.config.keymap = [
{
    name = "something";
    remap = {
        rightalt-a = { launch = [ ... ]; };
    };
}];
```

```nix
# modB.nix
services.xremap.config.keymap = [
{
    name = "something else";
    remap = {
        rightalt-b = { launch = [ ... ]; };
    };
}];
```

Only one of the two takes effect. This is probably due to (but haven't tested) how the option `services.xremap.config` is defined:

 https://github.com/xremap/nix-flake/blob/c8307a03099f4e07937ec781303f30f0909d29bb/lib/default.nix#L43-L46

Since this is a "freeform" attribute set and not a submodule, its members are not merged.
My suggestion would be to define the option like this instead:

```nix
    config = mkOption {
      type = types.submodule {
        options = {

          modmap = mkOption {
            type = types.listOf types.attrs;
            description = "...";
          };

          keymap = mkOption {
            type = types.listOf types.attrs;
            description = "...";
          };

        };
      };
      description = "...";
      default = { };
    };
  };
```

**Comment by VTimofeenko** [comment]
Related: #22

**Comment by VTimofeenko** [comment]
Should be fixed on master branch now, check plz

**Comment by VTimofeenko** [comment]
Have been running as part of checks for a while now, closing
