### ISSUE TITLE
How to make a sequence?

### ISSUE THREAD

**Issue by UnclePsymon** [xremap/nix-flake#75]
Hi! I want to bind sequences to launch applications. For example `super-alt` then `l` then `k` to launch Kitty or `super-alt` then `l` then `f` to launch Firefox. Could you give me an example on how to do this? I just can't get it to work. Thank you ❤️

**Comment by VTimofeenko** [comment]
This is better suited for [discussions in upstream repo](https://github.com/xremap/xremap/discussions).
